title: そこのけそこのけゆとりが通る
email: programmer@haizine.art
description: >- # this means to ignore newlines until "baseurl:"
  俳人データサイエンティストを目指してるフリーランスのWEBプログラマ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.regonn.tokyo" # the base hostname & protocol for your site, e.g. http://example.com
github_username: regonn
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - kramdown
  - jekyll-paginate

timezone: Asia/Tokyo
include: [".well-known"]
